### ISSUE TITLE
"to whomever" is valid usage of dative case

### ISSUE THREAD

**Issue by kriskowal** [theonlypwner/grammar#1]
https://twitter.com/kriskowal/status/566015658173820930

**Comment by theonlypwner** [comment]
Carefully read it again.

"to whomever is stenciling" is considered as "to (whomever is stenciling)"; "whomever is stenciling" is a noun phrase that does not depend on the preposition before it.

Within the noun phrase, "whomever" does not agree with "is" and should be replaced by "whoever" regardless of the "to" preceding it.

**Comment by theonlypwner** [comment]
I should add that `whomever` rarely appears in dative case, but here is an example: `whomever they gave it to`
