### ISSUE TITLE
"Less" vs "Fewer" corrections

### ISSUE THREAD

**Issue by gavinr** [theonlypwner/grammar#2]
Would love to see this respond when someone uses "less" where they should have used "fewer" - https://en.wikipedia.org/wiki/Fewer_vs._less

**Comment by theonlypwner** [comment]
None of the current corrections result in longer messages.
Otherwise, Twitter users would be correct to use the 140 character limit as an excuse.

Ironically, some Twitter users still mentioned the character limit even when the corrections shorten their original messages.
